### PR TITLE
Add cz lang

### PR DESCRIPTION
**Pull request by cewbdex**

### CODE REVIEW

**Comment by cleidigh** [comment]
@cewbdex 
Thanks for your draft pull req. I am always interested in making ImportExportTools as international as possible. This would be the 22nd locale!

Note: I see you have not done mboximport.dtd yet. That's good because I have just done a  cleanup which eliminates alot of deprecated entries.
You will not see this in master. If you can change your pr to merge into the v14.0.2 branch, that is what I am working on. You will also see the latest mboximport.dtd there.

Let me know when your PR is complete.
Thanks 
@cleidigh

**Comment by cewbdex** [comment]
Thanks, glad I did not start yet. Rebased and will finish it when I find a bit more time. I will probably not translate help page in this PR, I would like to do it at a later point, as it will require more time.

**Comment by cleidigh** [comment]
@cewbdex 
Great, no rush, I still have a lot to do for v14.0.2.
I have a special script to translate the help with Google. Yes never as good as a native, but it will be better than English and can be a start if you wish to improve.
Christopher

**Comment by cleidigh** [comment]
@cewbdex 
Checking in, v14.0.2 is getting close. I wanted to see if you still want to try to get this in?
If so note all dtd files have been converted to the messages.json 
Christopher

**Comment by cewbdex** [comment]
Hello there, I changed my job during the period, so I didn't have much spare time left, but I would continue in my work now, is there a way to convert it without doing it manually again? Thanks.

**Comment by cleidigh** [comment]
@cewbdex 
Hope your new job is going well!
So since your original PR all the dtd files have been converted into the messages.json. The properties files remain. Let me figure out the best way to deal with this and I will get back to you.
@cleidigh

**Comment by cleidigh** [comment]
@cewbdex 
Ok so we are missing mboximport.properties.
I can take the current PR and convert and merge the dtds. You can do a separate PR for the properties. I will also convert the help with my Google api script. Sound good?
@cleidigh

**Comment by cewbdex** [comment]
Yes, sure, thanks.

**Comment by cleidigh** [comment]
@cewbdex 
Wanted to check if you think you will be able to do mboximport.properties?
If not, I can do an auto translation which can be improved later.
@cleidigh

**Pull request merged**
